name : "DBManager"
version : 100

logger:
  logLevel : "info"                       # 打印级别 support debug/info/warning/error
  logOutToFile : true                     # 日志是否输出至文件
  logRotationSize : 10485760              # 文件切割大小 10MB
  logRotationCount : 14                   # 最多保存文件个数

rest:
  serverPort : 30001                      # REST server 端口号

